### ISSUE TITLE
tests are failing with SecurityException

### ISSUE THREAD

**Issue by vivekrathod** [legendary-code/process-domain#6]
I noticed this when I did a fresh clone yday..

test:
  Running tests, Debug ...
  src\AppSecInc.ProcessDomain.UnitTests\bin\Debug\AppSecInc.ProcessDomain.UnitTests.dll
  packages\NUnit.Runners.2.6.4\tools\nunit-console.exe /nologo src\AppSecInc.ProcessDomain.UnitTests\bin\Debug\AppSecInc.ProcessDomain.UnitTests.dll
  ProcessModel: Default    DomainUsage: Single
  Execution Runtime: net-3.5
  ..F.F..F.F.F.F..F.F
  Tests run: 11, Errors: 8, Failures: 0, Inconclusive: 0, Time: 5.46897330782416 seconds
    Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

  Errors and Failures:
NUNIT : 1) Test error : AppSecInc.ProcessDomain.UnitTests.TestProcessDomain.TestConfigurationLocation [E:\SOURCE\process-domain\ProcessDomain.proj]
     System.Runtime.Serialization.SerializationException : Because of security restrictions, the type System.Runtime.Remoting.ObjRef cannot be accessed.
    ----> System.Security.SecurityException : Request failed.

  Server stack trace:
     at System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject(Type type)
     at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(ParseRecord pr)
     at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
     at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
     at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
     at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
     at System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryRequestMessage(String objectUri, Stream inputStream, Boolean bStrictBinding, TypeFilterLevel securityLevel)
     at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHe
  aders& responseHeaders, Stream& responseStream)

  Exception rethrown at [0]:
     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
     at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
     at AppSecInc.ProcessDomain.Remoting.Activator.CreateInstanceAndUnwrap(String assemblyName, String typeName)
     at AppSecInc.ProcessDomain.ProcessDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName) in e:\SOURCE\process-domain\src\AppSecInc.ProcessDomain\ProcessDomain.cs:line 108
     at AppSecInc.ProcessDomain.UnitTests.TestProcessDomain.TestConfigurationLocation() in e:\SOURCE\process-domain\src\AppSecInc.ProcessDomain.UnitTests\TestProcessDomain.cs:line 183
  --SecurityException
     at System.Runtime.Serialization.FormatterServices.nativeGetSafeUninitializedObject(RuntimeType type)
     at System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject(Type type)

**Comment by gtrog** [comment]
Hmm I wonder if a newer version of NUnit runs things in a sandbox with fewer permissions?  That, or your local .NET security policy settings changed?

**Comment by vivekrathod** [comment]
I think its got something to do with the newer version, as I tried with the
older version 2.5.2 and it seemed to work...

**Comment by vivekrathod** [comment]
weird that using NUnit 2.5.2 as well Im seeing the same error...
but I noticed that setting the default value of TypeFilterLevel to Full
solves most of these issues except this one test TestTypeFilterLevel -
which expects that when the level is Low callbacks across the process
domain will not work.. but it seems that even regular object creation calls
w/o the use of callbacks also fail when the level is Low

**Comment by gtrog** [comment]
Could it have anything to do with removing the [Serializable] flag? When was the last time the unit tests passed for this?

**Comment by vivekrathod** [comment]
Which [Serializable] flag was removed? I remember proposing its removal on ActivatorHost and Activator but that was on the old codeplex site and I dont think you merged that patch

**Comment by vivekrathod** [comment]
aha may be this is what is causing it..
https://github.com/nunit/nunit/issues/522

**Comment by vivekrathod** [comment]
I confirmed this to be the case.. will move to NUnit 2.6.1 where this issue does not exist..

**Comment by gtrog** [comment]
Cool, thanks!
